[setting]
set_main_image = true              # メイン画像を設定するかどうか
save_parsed_data = true            # 解析データをJSONファイルに保存するかどうか
convert = false                    # MP3変換を実行するかどうか
debug = false                      # デバッグログを出力するかどうか
exclude_strings = ["SE無し", "SEなし", "効果音無し", "効果音なし", "_MACOSX"]  # 除外する文字列リスト

[dir_setting]
source_dir = "./data/source/"
html_dir = "./data/html/"
image_dir = "./data/image/"
output_dir = "./data/output/"
log_dir = "./data/log/"
mp3_output_dir_name = "mp3-output"